# Generated by Django 2.1.2 on 2018-10-20 16:41

from django.db import migrations, models
import django.db.models.deletion
import django_prices.models
import saleor.core


class Migration(migrations.Migration):

    operations = [
        migrations.RenameModel(
            old_name='PaymentMethod',
            new_name='Payment',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='payment_method',
            new_name='payment',
        ),
        migrations.AlterField(
            model_name='payment',
            name='checkout',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='checkout.Cart'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='order.Order'),
        ),
    ]
